schema: src/things/unreleased.yaml
target_class: ValueSpecification
data_sources:
  - src/things/unreleased/examples/ValueSpecification-01-minimal.yaml
  - src/things/unreleased/examples/ValueSpecification-02-quantitative-measurement.yaml
  - src/things/unreleased/examples/ValueSpecification-02-qualitative-assessment.yaml
plugins:
  JsonschemaValidationPlugin:
    closed: true
    include_range_class_descendants: false
  RecommendedSlotsPlugin:
