pid: ex:measurement853
attributes:
  - predicate: ex:title
    value: "measured mass (kg)"
characterized_by:
  # measurement datum
  - predicate: dcterms:type
    object: obo:IAO_0000109
  # mass
  - predicate: schema:about
    object: obo:PATO_0000125
  # unit: kilogram
  - predicate: obo:UO_0000000
    object: obo:UO_0000009
range: xsd:decimal
value: "145.3"
