pid: ex:assessment123
# personality
about:
  - obo:MF_0000202
# Character trait (observable entity) from snomed
kind: ex:sct-363881005
range: xsd:string
value: "Extrovert"
defined_by: ex:isbn-of-Jung-1923
