pid: marcrel:pdr
description: A person or organization with primary responsibility for all essential
  aspects of a project, has overall responsibility for managing projects, or provides
  overall direction to a project manager
annotations:
  skos:prefLabel: Project director
