id: exthisns:measurement853
has_attributes:
  - predicate: dcterms:title
    value: "measured mass (kg)"
is_characterized_by:
  # measurement datum
  - predicate: schema:about
    object: obo:IAO_0000109
  # mass
  - predicate: schema:about
    object: obo:PATO_0000125
  # unit: kilogram
  - predicate: obo:UO_0000000
    object: obo:UO_0000009
range: xsd:decimal
value: "145.3"
